---

- name: Get Homebrew user's uid
  command: id -u
  register: r_homebrew_user_uid
  changed_when: false
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"

- name: Set Homebrew user's uid
  set_fact:
    homebrew_user_uid: "{{ r_homebrew_user_uid.stdout }}"

- name: Get Homebrew user's gid
  command: id -g
  register: r_homebrew_user_gid
  changed_when: false
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"

- name: Set Homebrew user's gid
  set_fact:
    homebrew_user_gid: "{{ r_homebrew_user_gid.stdout }}"

- name: Create Homebrew directory
  file:
    path: "{{ homebrew_directory }}"
    state: directory
    owner: "{{ homebrew_user_uid }}"
    group: "{{ homebrew_user_gid }}"
    mode: "{{ homebrew_mode }}"
  become: true

- name: Clone Homebrew repository
  git:
    repo: "{{ homebrew_repository }}"
    dest: "{{ homebrew_directory }}"
    version: master
    update: false
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"

- name: Create required Homebrew directories
  file:
    path: "{{ homebrew_prefix }}/{{ item }}"
    state: directory
    owner: "{{ homebrew_user_uid }}"
    group: "{{ homebrew_user_gid }}"
    mode: "{{ homebrew_mode }}"
  with_items:
    - Caskroom
    - Cellar
    - Frameworks
    - bin
    - etc
    - include
    - lib
    - opt
    - sbin
    - share
    - var
  become: true

- name: Install Homebrew for given user
  block:
    - name: Locate the Homebrew cache
      command: "{{ homebrew_directory }}/bin/brew --cache"
      register: homebrew_cache
      changed_when: false
      check_mode: false

    - name: Create Homebrew cache
      file:
        path: "{{ homebrew_cache.stdout | trim }}"
        state: directory

    - name: Link brew binary
      file:
        src: "{{ homebrew_directory }}/bin/brew"
        dest: "{{ homebrew_prefix }}/bin/brew"
        state: link
      when: homebrew_directory != homebrew_prefix

    - name: Run brew update to complete installation
      command: "{{ homebrew_prefix }}/bin/brew update --force"
      environment:
        HOMEBREW_NO_ANALYTICS_THIS_RUN: "1"
        HOMEBREW_NO_ANALYTICS_MESSAGE_OUTPUT: "1"

    - name: Turn off analytics
      command: "{{ homebrew_prefix }}/bin/brew analytics off"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
