---

- import_playbook: setup.yml

- hosts: default
  environment:
    PATH: "{{ path | default(ansible_env.PATH) }}"
  pre_tasks:
    - name: Install Homebrew formula
      community.general.homebrew:
        name: starship
        path: "{{ homebrew_prefix }}/bin"
  roles:
    - role: config_starship
      tags: config_starship
